# Generated by Django 4.0.4 on 2022-05-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryTracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='deletion_comment',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
